#!/bin/bash
###Use queue (partition) q1
#SBATCH -p q1
### Use 1 nodes and 8 cores
#SBATCH -N 1 -n 10
#SBATCH --mail-user=21422885@life.hkbu.edu.hk
#SBATCH --mail-type=end
#SBATCH --time=40:00:00
# std oupt
#SBATCH -o job2.o

cd ${HOME}/FRL/FRL/fed_reg/
export conda_env=${HOME}/anaconda3/envs/frl
export PATH=${conda_env}/bin:${HOME}/anaconda3/condabin:${PATH}
export LD_LIBRARY_PATH=${conda_env}/lib:${LD_LIBRARY_PATH}

# echo "fedprox on pendulum std=1 no noisy input"
python dist_reg_v3.py --trial=3 --critic_partial=0.95
python dist_reg_v3.py --trial=3 --critic_partial=0.95
python dist_reg_v3.py --trial=3 --critic_partial=0.7
python dist_reg_v3.py --trial=3 --critic_partial=0.7

# python dist_reg_v3.py --trial=3 --critic_partial=0.5
# python dist_reg_v3.py --trial=3 --critic_partial=0.5
# python dist_reg_v3.py --trial=3 --critic_partial=0.9
# python dist_reg_v3.py --trial=3 --critic_partial=0.9
# python dist_reg_v3.py --trial=3 --critic_partial=0.95
# python dist_reg_v3.py --trial=3 --critic_partial=0.95
# python fed_scaffold.py
# python dist_reg_v2.py --trial=2
# python dist_reg_v3.py --trial=4
# python fedtd3_reg_walk.py --beta=0.01
# python fedtd3_reg_walk.py --beta=0.01
